import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
    id "com.modrinth.minotaur" version "2.+"
    id 'net.darkhax.curseforgegradle' version '1.1.26'
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}

def archivesName = "${mod_id}-${minecraft_version}-${project.name}-${version}"

modrinth {
    token = System.getenv("MODRINTH_MOD_PUBLISH")
    projectId = "beehave"
    versionName = archivesName
    versionNumber = version
    versionType = version.endsWith("a") || version.endsWith("alpha") ? "alpha" : version.endsWith("pre") ? "beta" : "release"
    uploadFile = jar
    gameVersions = [minecraft_version]
    loaders = ["neoforge"]
    File changelogFile = rootProject.file("changelog.md")
    if (changelogFile.exists()) {
        changelog = changelogFile.text
    }
    dependencies {
        required.project "fabric-api"
    }
}

tasks.register('curseforge', TaskPublishCurseForge) {
    apiToken = System.getenv("CURSEFORGE_MOD_PUBLISH")
    group = 'publishing'
    def mainFile = upload('880165', jar)
    mainFile.displayName = archivesName
    mainFile.releaseType = version.endsWith("a") || version.endsWith("alpha") ? "alpha" : version.endsWith("pre") ? "beta" : "release"
    File changelogFile = rootProject.file("changelog.md")
    if (changelogFile.exists()) {
        mainFile.changelog = changelogFile.text
    }
    mainFile.changelogType = 'markdown'
    mainFile.gameVersions = [minecraft_version]
    mainFile.addJavaVersion("Java 25")
    mainFile.addEnvironment("server", "client")
    mainFile.addModLoader("fabric")
    mainFile.addRequirement("fabric-api")
}