# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=0.1.0
maven_group=cool.muyucloud
archives_name=beehave-1.21.1
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.1
# Dependencies
architectury_api_version=13.0.8
neoforge_version=21.1.93

# Fabric properties
yarn_mappings=1.21.1+build.3
fabric_loader_version=0.16.9
# Fabric API
fabric_api_version=0.114.0+1.21.1